# Generated automatically from Makefile.doc.in by configure.
# 
#	$Id: Makefile.doc.in,v 1.1.2.2 2001/05/31 10:45:38 severijn Exp $
#

srcdir		= .

top_srcdir	= ..

subdirs		= clio ecbilt fixoc fixtim fom swamp tim

include ../config/make.macros


EXTRACFLAGS	=
EXTRACPPFLAGS	=
EXTRAFFLAGS	=
EXTRALDFLAGS	=
EXTRALIBS	=


distfiles=\
	Installation.html	\
	cko-logo-with-text.gif

dist_garbage = \
	Makefile

garbage =

more_garbage =


include ../config/make.rules


run: subdir_run

depend:	subdir_depend

install: subdir_install

install-strip: subdir_install-strip

main: subdir_main

uninstall: subdir_uninstall
