# Generated automatically from Makefile.doc.ecbilt.in by configure.
# 
#	$Id: Makefile.doc.ecbilt.in,v 1.1.2.1 2001/05/28 15:17:01 severijn Exp $
#

srcdir		= .

top_srcdir	= ../..


include ../../config/make.macros


EXTRACFLAGS	=
EXTRACPPFLAGS	=
EXTRAFFLAGS	=
EXTRALDFLAGS	=
EXTRALIBS	=


distfiles=\
	ecbilt.manual.tex

dist_garbage = \
	Makefile

garbage =

more_garbage =


include ../../config/make.rules


run:
	@echo Nothing to do for run

depend:
	@echo Nothing to do for depend

install:
	@echo Nothing to do for install

install-strip:
	@echo Nothing to do for install-strip

main:
	@echo Nothing to do for all

uninstall:
	@echo Nothing to do for uninstall
